# Generated by Django 3.2.14 on 2022-07-18 18:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cipher', '0004_alter_cipher_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_register', models.DateTimeField(verbose_name='Fecha Registro')),
                ('user_register', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario Registro')),
                ('code', models.CharField(blank=True, max_length=60, null=True, verbose_name='Codigo')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripcion')),
                ('image', models.ImageField(null=True, upload_to=product.models.product_image_file_path, verbose_name='Foto')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio')),
                ('deprecated', models.BooleanField()),
                ('cipher_code', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cipher.cipher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
